### ISSUE TITLE
Webpack zamiast rollup

### ISSUE THREAD

**Issue by piernik** [BEMQuery/bemquery-package-boilerplate#188]
Witam!

Jestem w trakcie lektury Twojej książki JS. Programowanie zaawansowane i bardzo mi się podoba - dobra robota.

Mam tylko jedno pytanie i prośbę.

Dlaczego nie Webpack?? Wydaje się on lepszym wyborem choćby przez to że angular2 właśnie z webpackiem się związał na stałe.

Czy mógłbyś zrobić boilerplate z webpackiem?

**Comment by Comandeer** [comment]
> Wydaje się on lepszym wyborem choćby przez to że angular2 właśnie z webpackiem się związał na stałe.

I właśnie ten powód przesądza… ;)

A tak bardziej na poważnie: nie widzę sensu w pchaniu takiej kobyły jak WebPack do w sumie tak prostego projektu. Nie ma tutaj ani CSS-a, ani innych zasobów, raptem kilka plików JS na krzyż. W tym momencie nie wykorzystywałbym praktycznie żadnych możliwości WebPacka – jedynie możliwość łączenia plików JS w jeden.

A akurat w tym [WebPack był zdecydowanie gorszy od rollupa](https://nolanlawson.com/2016/08/15/the-cost-of-small-modules/) i nie sądzę, żeby aż tak się poprawił – zwłaszcza, że przecież musi obsługiwać nie tylko moduły ES. Nie zyskałbym nic przechodząc na WebPacka – no, może oprócz większego community ;)

Więc na chwilę obecną takich planów nie ma, zostaje rollup. Jak projekt się rozrośnie na tyle, że pojawi się coś więcej niż JS (choć wątpię), to wówczas zastanowię się ponownie nad WebPackiem.

**Comment by piernik** [comment]
Może trochę się źle wyraziłem - nie miałem na myśli zmienianie tego projektu, ale utworzenie nowego boilerplate'a z webpackiem.

PS. Czytałem, że webpack 2 tworzy mniejsze pliki boundle niż rollup - https://gist.github.com/forabi/2a538b263d0f1fe5f041
PS2. Widzę, że angular nie przypadł do gustu :)

**Comment by Comandeer** [comment]
> PS. Czytałem, że webpack 2 tworzy mniejsze pliki boundle niż rollup

https://gist.github.com/forabi/2a538b263d0f1fe5f041#gistcomment-1923113 – to nie wróży dobrze temu benchmarkowi ;) https://github.com/samccone/The-cost-of-transpiling-es2015-in-2016 – ten wygląda bardziej przekonująco i tutaj różnice nie są aż tak duże. Co ciekawe, TS + WP1 wypada lepiej niż standardowy zestaw z WP2.

> PS2. Widzę, że angular nie przypadł do gustu :)

Angular 2 wygląda o niebo lepiej niż Angular 1, ale to IMO wciąż przekombinowana, przyciężkawa kobyła.

Co do osobnego boilerplate'a: prawdę mówiąc nie widzę w tym sensu. Nie zyska się dzięki temu nic (a jak już, to wyciśnie kilkadziesiąt bajtów na bundle'u). Nawet nie ma za bardzo co mówić o zwiększeniu kompatybilności z WP, bo przecież na npm i tak wszystkie paczki oparte na tym boilerplate są rozprowadzane jako gotowy do wykorzystania moduł – zatem są kompatybilne ze wszystkim. Na razie zatem się wstrzymam z tworzeniem drugiej wersji.
