### ISSUE TITLE
Typo in config/rollup/es5.js

### ISSUE THREAD

**Issue by logarytm** [BEMQuery/bemquery-package-boilerplate#189]
I think template strings should be used [here](https://github.com/BEMQuery/bemquery-package-boilerplate/blob/0c343de0d2069aee500697edeb57abd05fed9003/config/rollup/es5.js#L15).

**Comment by Comandeer** [comment]
Fixed with 7f17640cf1fa7ca439ef7d4bc6e8250ef20b7485.
