### ISSUE TITLE
Badges are broken

### ISSUE THREAD

**Issue by jcubic** [BEMQuery/bemquery-package-boilerplate#207]
Image badges in readme are broken

**Comment by Comandeer** [comment]
Actually there isn't a sensible way to fix it in boilerplate – badges just point to the non-existent package. In [normal package (e.g. `bemquery`)](https://github.com/BEMQuery/bemquery#bemquery) everything's working fine (although david-dm.org seems to have some troubles recently…).

**Comment by jcubic** [comment]
you can remove them from boilerplate.

**Comment by Comandeer** [comment]
Yes, I can, but I don't want to ;)

With the current boilerplate creating new repo for new package requires only to change package's name and everything's done – even badges are already in place. Therefore I don't see much harm in not working badges.

**Comment by Comandeer** [comment]
Seems like the issue is explained.
